### ISSUE TITLE
it doesn't hide the side panel

### ISSUE THREAD

**Issue by wertasdfg999** [fanfare/disablegooglelens#3]
![螢幕擷取畫面 (2623)](https://user-images.githubusercontent.com/120352477/206955093-a5f810c6-0131-4663-ae1b-49366d239c05.png)

**Comment by fanfare** [comment]
in the right click menu, use the option 'Search Google for image' (the one with the magnifying glass next to it) instead of 'Search image with Google Lens'
there are instructions to hide the old 'Search image with Google Lens' item (which opens images in the side tab) here: [https://github.com/fanfare/disablegooglelens/blob/master/CHROME.md](https://github.com/fanfare/disablegooglelens/blob/master/CHROME.md)
